spring.application.name=coffee-delivery

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.main.allow-bean-definition-overriding=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

spring.security.oauth2.client.registration.github.client-id=f
spring.security.oauth2.client.registration.github.client-secret=f
spring.security.oauth2.client.registration.github.redirect-uri=f
spring.security.oauth2.client.registration.github.scope[0]=read:user
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
